### ISSUE TITLE
create a good readme file 

### ISSUE THREAD

**Issue by Raja-Debnath** [Mr-Ayushh/MAXUS#1]
@Mr-Ayushh 

1. describe the project 
2. technologies used 
3. how to install and configure

**Comment by Mr-Ayushh** [comment]
Ok sirr 👍🏻🫡

**Comment by Mr-Ayushh** [comment]
> @Mr-Ayushh 
> 
> 1. describe the project 
> 2. technologies used 
> 3. how to install and configure

Ok sirr 👍🏻🫡
